_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True
  WEIGHTS: weights/market_agw_R101-ibn.pth
DATASETS:
  NAMES: ("Worm",)
  TESTS: ("Worm",)

OUTPUT_DIR: logs/Worm/agw_R101-ibn
